sync 오류 해결 및 eslint 오류 가이드 추가 (#11)
* feat: [ODPLFE-233] sync 워크플로우에서 PERSONAL_ACCESS_TOKEN 이 설정되지 않았다면 동기화를 진행하지 않음

* feat: [ODPLFE-233] eslint 설정 오류 가이드 추가

* feat: [ODPLFE-233] readme.me 내 불필요한 문제 제거 및 회사명 기재

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -12,6 +12,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # PERSONAL_ACCESS_TOKEN 이 설정되지 않았다면 더이상 진행하지 않음
+      - name: Check if PERSONAL_ACCESS_TOKEN is set
+        run: |
+          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
+            echo "Error: PERSONAL_ACCESS_TOKEN is not set"
+            exit 1
+          fi
+        shell: bash
+
       # fork 된 리포지토리 체크아웃
       - name: Checkout forked repository
         uses: actions/checkout@v4
